CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  description TEXT NULL,
  github_repo VARCHAR(120) NOT NULL,
  dev_subdomain VARCHAR(120) NOT NULL,
  prod_subdomain VARCHAR(120) NOT NULL,
  dev_dir VARCHAR(255) NOT NULL,
  prod_dir VARCHAR(255) NOT NULL,
  dev_db_name VARCHAR(64) NOT NULL,
  prod_db_name VARCHAR(64) NOT NULL,
  default_branch VARCHAR(40) NOT NULL DEFAULT 'dev',
  prod_branch VARCHAR(40) NOT NULL DEFAULT 'main',
  card_tint ENUM('peach','rose','mint','lavender','sky','yellow') NOT NULL DEFAULT 'peach',
  status ENUM('provisioning','active','archived') NOT NULL DEFAULT 'provisioning',
  last_synced_commit VARCHAR(40) NULL DEFAULT NULL,
  last_synced_at TIMESTAMP NULL DEFAULT NULL,
  last_prod_commit VARCHAR(40) NULL DEFAULT NULL,
  last_prod_deployed_at TIMESTAMP NULL DEFAULT NULL,
  init_job_id INT UNSIGNED NULL DEFAULT NULL,        -- no FK: circular ref with jobs (jobs.project_id → projects)
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
